### ISSUE TITLE
I think the :asset-path option should have same behavior with boot-cljs.

### ISSUE THREAD

**Issue by gfZeng** [adzerk-oss/boot-reload#34]
the file for/bar.js with {:asset-path "/static/some.out"} should generate path like this: /static/some.out/for/bar.js

**Comment by piranha** [comment]
+1, I serve all static files under `/static` folder and there is no way to tell boot-reload that it should be reloading from `/static/main.out` rather than `/main.out`.

**Comment by Deraen** [comment]
@piranha Should work if the files are inside static folder in fileset (and classpath):

`(resources "/static" {:root "public/static"})`

You can either move your source files so that the resulting files are in right path or use `sift` to move files.

Something should be done to have same behavior for `asset-path` but I don't know what would be the solution. A quick fix could be to use map of regex and replacements for asset-path, but it is not good solution.

The solution for these asset-path problems once and for all will probably require that there is some clear relation between paths in fileset and paths in web. `js/main.js` -> `js/main` is the simplest and sanest but `public/js/main.js` -> `js/main.js` also makes sense. Not sure if `public/js/main.js` -> `static/js/main.js` should ever be supported, but `public/static/js/main.js` -> `static/js/main.js` should be.

**Comment by piranha** [comment]
I'm not sure I get your reasons. I'm serving my target folder myself, and I want to serve it on a certain path, which is not connected to the path on the disk. 

With figwheel I have following options for compiler defined:

```{:output-to            "target/main.js"
 :output-dir           "target/main.out"
 :asset-path           "/static/main.out"}```

and with that it works with no further configuration. `boot-cljs` also works as intended, puts files in desired location and with expected urls inside, but then `boot-reload` tries to reload them based on their location on disk.

I'm not exactly sure what's the right way to approach that, though.

**Comment by Deraen** [comment]
@piranha I'm not sure what you are trying to do, Boot-cljs doesn't allow you to set `output-to` or `output-dir`. It will always overwrite those options.

**Comment by piranha** [comment]
Ah, right, that's true. For boot I only have `:asset-path` set. :)
