### ISSUE TITLE
Cljs-asset-path should end up in js file?

### ISSUE THREAD

**Issue by arichiardi** [adzerk-oss/boot-reload#97]
There is a question mark because I am not sure about this.

We have a `serve` task serving assets on `http://localhost:8000` and therefore our js (even if it is `dev`) is served from there. We have the following `division.cljs.edn` in place:

```
{:require  [division.app]
 :init-fns [division.app/init]
 :compiler-options {:asset-path "/division.out"}}
```

And I tried to add `:cljs-asset-path` to the `boot-reload` compiler options:

`:cljs-asset-path "http://localhost:8000"`

However the result is, and maybe I am misinterpreting the option:

![2016-10-12-200250_678x99_scrot](https://cloud.githubusercontent.com/assets/1724788/19335332/433559a8-90b7-11e6-9cda-5c362a2bb71d.png)

The only way I could make it work was by intercepting the `cljs.edn` file(s), and patching them to:

```
{:require  [division.app]
 :init-fns [division.app/init]
 :compiler-options {:asset-path "http://localhost:8000/division.out"}}
```

I wonder though if I am doing something wrong or I can improve on this somehow (a PR is included in the list of improvements :smile:).

Thanks @Deraen for your work on `boot-reload` as usual!

**Comment by Deraen** [comment]
Boot-reload should load the assets from the same host and port as you have open in browser. You can use `asset-host` option if you need to change this.

Due to "ClojureScript could not load :main` error, it looks like your application can't load even initially. That error can't be caused by Boot-reload because Boot-reload will only do anything after Cljs app has been successfully evaluated. And boot-reload doesn't affect Clojurescript output at all.

**Comment by arichiardi** [comment]
Sorry, everything you said is true of course and this is more like a `boot-cljs` issue. Closing.
